### ISSUE TITLE
Implement Spellchecker

### ISSUE THREAD

**Issue by abb128** [futo-org/android-keyboard#1334]
### Use Cases

Android has a built-in spellchecker feature that is on by default. This highlights misspelled words and suggests corrections.

Spellchecker is usually provided by the same app as the keyboard, but as this is not implemented currently, users will be using a different spellchecker. This causes problems such as red underlines under every word when typing in another language.

Users can resolve this by disabling the spellchecker in Android settings but this is not ideal. 

### Proposal

Implement a spellchecker that respects current keyboard language and multilinguality settings

**Comment by colvdv** [comment]
I notice that I don't have the underline at all when I mispell a word. Autocorrect does its best to choose what it thinks but if there is a typo and I don't notice, there is no red underline to make it stand out.

**Comment by Zvonimir-FUTO** [comment]
> I notice that I don't have the underline at all when I mispell a word. Autocorrect does its best to choose what it thinks but if there is a typo and I don't notice, there is no red underline to make it stand out.

Try to search for Spellchecker inside your system settings and see if it's turned on and for which language.
Also this could depend on the input field on which you are typing.

**Comment by PhoenixIV** [comment]
It seems like there is spell checking now after the latest update.

However:

It only works with my systems main language (German) and not with my systems secondary language (English (Germany)).

So all english words are underlined, even if the keyboard language is also set to English.

The spell check language in the Android settings is set to "system languages", not just a single language. 

The spell checker is still set to Android (AOSP), as it was for months.

There is no other spell checker available.

Bug.

**Comment by abb128** [comment]
@PhoenixIV There is no spellchecker yet, you're still using your system spellchecker it seems

**Comment by PhoenixIV** [comment]
Huh, that is weird! It did not work and now it suddenly does. I also skipped a few futo versions. If it was not caused by the futo update maybe it was caused by a system update...

**Comment by MattDupraz** [comment]
There does not seem to be any option for the spellchecker in my system settings (OnePlus Nord 2T), this seems to be handled by the keyboard. Gboard has an option to enable/disable the spellchecker, and its spellchecker works flawlessly, so this should be something implemented from by the keyboard app.

I have the same issue as OP: whenever I type in a language different from the system language, I get red underlines everywhere and English correction suggestions, it's quite irritating.

**Comment by alexw-at** [comment]
This would be helpful, I often switch between two languages

**Comment by trespaul** [comment]
> Try to search for Spellchecker inside your system settings

If anyone else is looking for this setting but can't find it, mine was in the gboard settings. One would think that gboard settings would only take effect when using gboard, but apparently that counts as the built-in spellchecker.

**Comment by laundmo** [comment]
Note: FlorisBoard could be used as a example to learn how exposing a system spell checking service could work

https://github.com/florisboard/florisboard/blob/main/app/src/main/kotlin/dev/patrickgold/florisboard/FlorisSpellCheckerService.kt#L19

**Comment by HoroTW** [comment]
I thought FUTO was broken because of this issue - nearly all the words were underlined in red.
From a user experience point of view, this is a real issue.

**Comment by abb128** [comment]
@HoroTW The underlines should be fixed in next release (including 0.1.26-rc1) although this is done by disabling the spellchecker completely rather than implementing a working one

**Comment by VoxelPrismatic** [comment]
PLEASE
My phone doesn't have a system spell checker other than GBoard, and GBoard is unreliable because it puts itself to sleep when the keyboard app isn't used.

**Comment by Renalds-B** [comment]
Any updates for this?

**Comment by SparWiz-Khalifa** [comment]
This is still an issue. I only have Heliboard as my Spellchecker on my GrapheneOS phone, but it only works with HeliBoard. I would like to switch to FUTO, as it has some nice features, but it also lacks some important ones, such as spellchecker which is kind of a dealbreaker, unfortunately

**Comment by FibroJedi** [comment]
What's weird, is that FUTO works fine on my galaxy S23 phone,  but on my Galaxy tablet spelling errors are not underlined. I don't want to use Gboard for personal reasons,  and Samsung Keyboard seems to only serve half of its job. So, I'm off to find an alternative for my tablet.

**Comment by fredgolightly** [comment]
Cannot get any spell check working with Futo, have gboard and Samsung keyboard installed too
